### ISSUE TITLE
Add list examples

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-markdown#3]
Add unordered and ordered list examples. For unordered, you use ` - `, and for ordered use numbers:

```md
 1. Item 1
 2. Item 2
```

**Comment by Toddsqui** [comment]
This is my first unordered list:
-Bananas
-Grapes
-Rainbows
-Unicorns

This is my first ordered list:
1. Cow
2. Monkey
3. Horse

**Comment by Toddsqui** [comment]
Wasn't sure how the text was made red.

**Comment by IonicaBizau** [comment]
@Toddsqui Add them in `README.md` using ```` ```md ```` code blocks.
